// Generated by https://quicktype.io

class Solicitud {
  String id;
  String jugador;
  String fechaEnviado;
  dynamic fechaAprobado;
  bool esSeleccionado;

  Solicitud({
    this.id,
    this.jugador,
    this.fechaEnviado,
    this.fechaAprobado,
    this.esSeleccionado
  });

  factory Solicitud.fromJson(Map<String,dynamic> json){
    return Solicitud(
      id: json['Id'],
      jugador: json['Jugador'],
      fechaEnviado: json['FechaEnviado'],
      fechaAprobado: json['FechaAprobado'],
      esSeleccionado: true
    );
  }
}
