// Generated by https://quicktype.io

class Solicitud {
  String id;
  String jugador;
  String fechaEnviado;
  dynamic fechaAprobado;

  Solicitud({
    this.id,
    this.jugador,
    this.fechaEnviado,
    this.fechaAprobado,
  });

  factory Solicitud.fromJson(Map<String,dynamic> json){
    return Solicitud(
      id: json['Id'],
      jugador: json['Jugador'],
      fechaEnviado: json['FechaEnviado'],
      fechaAprobado: json['FechaAprobado'],
    );
  }
}
