// Generated by https://quicktype.io

class Curso {
  String id;
  String nombre;
  String descripcion;
  String organismoId;
  String organismoNombre;
  String armaId;
  String armaNombre;

  Curso({
    this.id,
    this.nombre,
    this.descripcion,
    this.organismoId,
    this.organismoNombre,
    this.armaId,
    this.armaNombre,
  });

  factory Curso.fromJson(Map<String,dynamic> json){
    return Curso(
      id : json['id'],
      nombre : json['nombre'],
      descripcion : json['descripcion'],
      organismoId : json['organismoId'],
      organismoNombre : json['organismoNombre'],
      armaId : json['armaId'],
      armaNombre : json['armaNombre'],
    );
  }
}
